# load balancer for calculations
# see also simple example in Compose25a.yaml
services:
  calculator:
    image: devopsdockeruh/scaling-exercise-calculator
    ports:
      - 3000:3000
    container_name: calculator
  compute:
    image: devopsdockeruh/scaling-exercise-compute
    environment:
      - VIRTUAL_HOST=compute.localtest.me
  load-balancer:
    build: ./load-balancer
    image: load-balancer
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - 80:80
    container_name: load-balancer
# docker compose up -d --scale compute=10
