name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "express-app/**"
      - ".github/workflows/pipeline.yml"

jobs:
  build-and-push-image: # name of the job
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # should be included in build-push-action
      # - name: Checkout repository
      #   uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:express-app"
          # platforms: linux/amd64,linux/arm64
          platforms: linux/arm64
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/container-ex-express-app:latest
